[workspace]
members = [
    "nomos-core",
    "nomos-libp2p",
    "nomos-services/log",
    "nomos-services/metrics",
    "nomos-services/network",
    "nomos-services/storage",
    "nomos-services/consensus",
    "nomos-services/mempool",
    "nomos-services/http",
    "nomos-da-core/reed-solomon",
    "nomos-da-core/kzg",
    "nodes/nomos-node",
    "simulations",
    "consensus-engine",
    "tests",
]
