[workspace]
members = [
    "nomos-core",
    "nomos-services/log",
    "nomos-services/metrics",
    "nomos-services/network",
    "nomos-services/storage",
    "nomos-services/consensus",
    "nomos-services/mempool",
    "nodes/nomos",
    "nodes/mempool-metrics",
]