[workspace]
members = [
    "nomos-core",
    "nomos-libp2p",
    "nomos-services/log",
    "nomos-services/metrics",
    "nomos-services/network",
    "nomos-services/storage",
    "nomos-services/consensus",
    "nomos-services/mempool",
    "nomos-services/http",
    "nomos-services/data-availability",
    "nomos-services/system-sig",
    "nomos-da/reed-solomon",
    "nomos-da/kzg",
    "nomos-da/full-replication",
    "nomos-http-api",
    "nomos-cli",
    "nodes/nomos-node",
    "nodes/mixnode",
    "simulations",
    "consensus-engine",
    "tests",
    "mixnet/node",
    "mixnet/client",
    "mixnet/protocol",
    "mixnet/topology",
]
resolver = "2"