[workspace]
members = [
    "nomos-core",
    "nomos-services/log",
    "nomos-services/metrics",
    "nomos-services/network",
    "nomos-services/storage",
    "nomos-services/consensus",
    "nomos-services/mempool",
    "nomos-services/http",
    "nodes/nomos-node",
    "nodes/mockpool-node",
    "simulations",
    "consensus-engine"
]
