backend:
  host: "127.0.0.1"
  port: 8000
  mixnet_client:
    # A mixclient mode. For details, see the documentation of the "mixnet" crate.
    # - Sender
    # - !SenderReceiver [mixnode_client_listen_address]
    mode: Sender
    # A mixnet topology, which contains the information of all mixnodes in the mixnet.
    # (The topology is static for now.)
    topology:
      # Each mixnet layer consists of a list of mixnodes.
      layers:
        - nodes:
          - address: 127.0.0.1:7777  # A listen address of the mixnode
            # A ed25519 public key for encrypting Sphinx packets for the mixnode
            public_key: "0000000000000000000000000000000000000000000000000000000000000000"
    connection_pool_size: 255
    max_retries: 5
    retry_delay: 
      secs: 1
      nanos: 0
  mixnet_delay:
    start: "0ms"
    end: "0ms"
