[package]
name = "reed-solomon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reed-solomon-erasure = "6.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "nomos_rs"
harness = false
