[package]
name = "mempool-metrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
overwatch-rs = { git = "https://github.com/logos-co/Overwatch", branch = "main" }
overwatch-derive = { git = "https://github.com/logos-co/Overwatch", branch = "main" }
tracing = "0.1"
metrics = { path = "../../nomos-services/metrics" }
nomos-log = { path = "../../nomos-services/log" }
nomos-network = { path = "../../nomos-services/network", features = ["waku"] }
nomos-mempool = { path = "../../nomos-services/mempool" }
tracing-subscriber = "0.3"
serde_yaml = "0.9"
color-eyre = "0.6.0"
serde = "1"