[package]
name = "nomos-kzg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kzg = { git = "https://github.com/sifraitech/rust-kzg.git", package = "rust-kzg-blst", features = ["parallel"] }
kzg_traits = { git = "https://github.com/sifraitech/rust-kzg.git", package = "kzg" }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "nomos_kzg"
harness = false
